apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/avoidGit/agrocd-test.git
    path: apps/mynginx
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc 
    namespace: default
  syncPolicy:
    automated:
      prune: true   # удалять ресурсы, если их убрали из Git
      selfHeal: true # автоматически восстанавливать состояние, если оно изменилось вручную
